import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/footer";
import ReactQueryProvider from "@/providers/QueryProvider";
import BookmarkProvider from "@/providers/BookmarkProvider";

const poppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Real_Estate_JSX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppinsFont.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <BookmarkProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </BookmarkProvider>
      </body>
    </html>
  );
}
